// The full "Shit Happens: Spring 2020 Edition" deck.
//
// Cards are listed in ascending order of misery. The Misery Index in the
// printed game runs 1 -> 100 in 0.5 steps. A few index numbers in the source
// PDF were unreadable (overlapping text), so indices here are assigned
// POSITIONALLY (1, 1.5, 2, 2.5, ...). This preserves the exact relative
// ordering of every card -- which is the only thing the game logic depends on
// -- while keeping the numbers clean. The number is kept SERVER-SIDE and only
// revealed to clients after a guess is resolved.
//
// Card text is reproduced verbatim from the deck (crude content intentional).

const ORDERED_SITUATIONS = [
  "Brain Freeze",
  "Step on Lego® in Bare Feet",
  "Kid Downloads Virus",
  "Shampoo in Eyes",
  '"Baby Shark" Stuck in Your Head',
  '"Let It Go!"',
  "Discovery: Parents Were Swingers",
  "Unsolicited Dick Pics",
  "You Took Home the Class Pet for Spring Break",
  "Acne Outbreak on Your Butt",
  "It's Raining Again!",
  "Kid Prank Calls 9-1-1",
  'Kid Walks in on "Snuggle-Time"',
  "Facial Hair Only Grows into a Hitler 'Stache",
  "Modern Family Ends",
  "Dead Batteries",
  "Clog the Toilet",
  'Discover Your Spouse is "That Guy" on Conference Calls',
  'Bass Line From "Under Pressure" Stuck in Your Head',
  "Bed Crumbs",
  "First Grey Hair",
  "First Grey Pubic Hair",
  "You Haven't Gotten to Watch Tiger King Yet",
  "Drink Coffee With a Dead Cigarette in It",
  "You Have to Clean Your Own House",
  "The Only Beer Left is Crap Your Cousin Left Last Summer",
  "Therapist Tries to Get You to Join Her Sexy MLM",
  'Grandma Calls Herself a "GILF"',
  "Noise Complaint at Your House",
  "You Get Zoombombed",
  "Learn Your Partner is a Joe Exotic Apologist",
  "Not Even Bots Match You on Tinder",
  "Bed Bugs",
  "Kid Convinces Sibling They're Adopted",
  "Kid Changes Wi-Fi Password",
  "Telemarketer Calls",
  "Your Dog Goes Into Heat",
  "Your Dog Is Incontinent",
  "Cat Refuses to Use the Litter Box",
  "Cat Turds on Carpet; You Don't Own a Cat",
  "Your Hand Sanitizer is Expired",
  "Roommate Complains About Sex Life While You're on a Conference Call",
  "Drunk Text Your Ex",
  "Bird Shits on Head",
  "Kid Gives Dog Peanut Butter Bath",
  "You Get Gum in Your Hair",
  "Kid Punches Hole in Wall",
  "Toy Breaks Vacuum",
  "Bed Breaks",
  "Schitt's Creek Ends",
  "The Great Yeast Shortage of 2020",
  "Wifi Bus Contains a Polka Band",
  "You Finished Netflix",
  "You Have Watched Every White House Briefing",
  "No WIFI",
  "Internet Drops, Corrupts 10GB File You Were Downloading",
  '"Can We Keep It?"',
  "Those Season Tickets are Gathering Dust",
  "Break Your Glasses",
  "Roommate Drinks All Your Beer",
  "DVR Glitch...All Shows Erased",
  "Shit the Bed",
  "Head Lice",
  "Ingrown Toenail",
  "Hear a Noise Outside While Watching a Serial Killer Documentary",
  "No Cell Phone Signal",
  "Program Crashes While You're Saving Work",
  "Package Gets Stolen off Your Front Porch",
  "Fall Asleep and Snore on a Skype Conference Call",
  "Quarantine Self-Haircut",
  "Your New Neighbor Is OJ",
  "No One Wants a Virtual Happy Hour With You",
  "Accidentally Sext Your Mom",
  "Dog Ate Your Condoms",
  "Can't Get a Grocery Delivery for 9 Days",
  "Dog Brings Out Dildo",
  "TikTok Shocker: Grandpa in Dog Collar",
  "Marbles Lodged in Nose",
  "Your Partner Develops a Thing for Clowns",
  "Fall Down a Flight of Stairs",
  "Lose Hot Water",
  "You're Out of Booze",
  "Diarrhea, No Toilet Paper",
  "Earbud Gets Stuck in Your Ear",
  "Metal in the Microwave",
  "Skunk in Your House",
  "Move Back in With Your Parents",
  "Kid Stuck in Tree",
  "Extremely Upsetting Dream",
  "The Same Movie Over and Over",
  "A Cold... or Something More Serious?",
  "Develop an Allergy to Your Favorite Food",
  "Live Rat in Your Toilet",
  "Actual Pants No Longer Fit",
  "You Took Unsubstantiated Medical Advice",
  "Failed Homework; You Helped",
  "Heater and AC Break",
  "No Bathroom Privacy",
  "Accidentally Shared Porn",
  "A Raccoon Has Moved In",
  "Possums in Your Attic",
  "Raccoons Get into Your House Through the Doggy Door",
  "Your Roommate is a Conspiracy Theorist",
  "Unclog Toilet With Your Bare Hands",
  "Four-Day Power Outage",
  "Put on Your Sock, and There's a Scorpion in It",
  "Down to Your Last Square of Toilet Paper",
  "Someone From the Balcony Above Vomits on You",
  "Teen Dyes Their Own Hair",
  "Clingy Relationship",
  "Your Significant Other Is a Pillow",
  "Find Your Grandmother's Bag of Toys",
  "Slice Your Finger Opening a Can of Beans",
  "Dog Eats Your Wedding Ring",
  "You Find Your Mom's Dildo Collection",
  "Condom Stuck in Vagina",
  "Locked Out of Your House While Naked",
  "Your Employer Bounces Your Paycheck",
  "New Sex Experiment Leads To Pink Eye",
  "That Toilet Paper You Hoarded? It Has Splinters",
  "Brother Masturbated Into All Of Your Socks",
  "Spouse Shits the Bed",
  "All-Day Migraine",
  "You Can't Shit For a Week",
  "Phone Falls in Toilet",
  "Cracked Cell Phone Screen",
  "Lose Your Laptop",
  "Lose a Fingernail",
  "Lose a Toenail",
  "There Is Piss On Everything",
  "A Spider Crawls into Your Ear",
  "Nipple Piercing Gets Ripped Out",
  "You're the Only Person At Your Birthday Party",
  "You Shit Yourself Right Now, While Playing This Game",
  "Dick Stuck in Vacuum Cleaner",
  "That New House You Bought? It's Haunted",
  "Basement Floods",
  "Pipes Freeze",
  "Spouse's Racist Rant Goes Viral",
  "Ripped Condom",
  "Develop Allergy to Alcohol",
  "Chronic Insomnia",
  "Pass a Kidney Stone",
  "Police Mistakenly Storm Your House",
  "You're Accused of Hoarding PPE",
  "Find Your Mom's Erotica Fanfiction Online",
  "Mom Keeps Going Out in Public",
  "Your Parents Aren't Practicing Social Distancing",
  "Gout",
  "Sick on Bad Liquor",
  "You Took a Gamble on Recently Expired Milk",
  "Ben Wa Balls Get Stuck",
  'That "Private" Zoom Chat Makes it Into the Transcript',
  "Uh-Oh! You Forgot Your Safe Word",
  "Tinder Notification on Spouse's Phone",
  "Your Last Phone Charger Died",
  "Upstairs Neighbor's Son Gets Drum Kit",
  "Brother Nairs Sister's Head",
  "Go Bald",
  "Lose All Hair, Everywhere",
  "Washer and Dryer Break",
  "Electricity Is Cut Off",
  "Wardrobe Malfunction on a Zoom",
  "You Develop John Finlay Teeth",
  "Two-Week Migraine",
  "Incurable Hiccups",
  "Develop Agoraphobia, Cannot Leave House",
  "Toilet Overflows and Floods Your House",
  "Fall into Septic Tank",
  "Tree Falls on Your House",
  "Realize Your Spouse Is a Furry",
  "Heavy Web Traffic, Can't File Unemployment",
  "Rats Infest Your Neighborhood",
  "Roommate Throws A Party",
  "Find Grandpa's Diary; He Was a Nazi",
  "Watch a Porn Video of Your Parents",
  "Watch a Porn Video OF Your Parents, WITH Your Parents",
  "Everyone Else in Your Department is Laid Off; Guess Whose Workload Just Quintupled?",
  "Furloughed; You Resort to Selling Clothes Online",
  "Your Job is Outsourced",
  "You Decided to Go on a Cruise",
  "Tapeworm",
  "Identity Stolen",
  "Dislocated Kneecap Mid-Thrust",
  "Accidentally Post a Nude Picture on Facebook",
  "Computer Gets Hacked",
  "Anal Beads: 10 Go In, 7 Come Out",
  "The Newly Installed Bidet Spouts Boiling Water",
  "Ex Drains Your Bank Accounts",
  "Cell Phone Blows Up in Your Face",
  "Mauled by a Tiger",
  "Addicted to Heroin",
  "Dr. Phil Becomes the Nation's Foremost Health Expert",
  "Your House Burns Down",
  "Dr. Fauci Quits",
  "Dr. Oz Becomes the Nation's Foremost Health Expert",
  "House Accidentally Demolished",
  "Your Roommate Brings Home Corona (Not the Beer)",
  "Carole Baskin Shows You Her Meat Grinder",
];

// Assign a stable id and a positional Misery Index (1, 1.5, 2, ...).
const DECK = ORDERED_SITUATIONS.map((text, i) => ({
  id: i + 1,
  text,
  index: 1 + i * 0.5,
  img: `card-${String(i).padStart(3, '0')}.jpg`,
}));

module.exports = DECK;
